[package]
name = "bostil-bot"
authors = ["Cassiano Rodrigues <kszinhu@modscleo4.dev.br>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.18"
serenity = { default-features = false, features = ["cache", "client", "gateway", "rustls_backend", "model"], version = "0.11.6" }
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }