[workspace]
resolver = "2"
members = ["app", "core"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.package]
authors = ["Cassiano Rodrigues <kszinhu@modscleo4.dev.br>"]
edition = "2021"

[workspace.dependencies]
# Discord
serenity = { default-features = false, features = [
  "cache",
  "client",
  "http",
  "framework",
  "standard_framework",
  "gateway",
  "voice",
  "rustls_backend",
  "model",
  "collector",
], version = "0.12" }
songbird = { features = ["builtin-queue"], version = "0.5" }

# Database
postgres = { version = "0.19" }
tokio-postgres = { version = "0.7.10" }
diesel = { version = "2", features = ["postgres", "chrono", "uuid"] }
diesel_migrations = { version = "2" }
chrono = { version = "0.4", features = ["serde"] }

# Internationalization
rust-i18n = { version = "3" }
serde_yaml = "*"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tracing-futures = "0.2"

# Other
reqwest = { version = "0.12", default-features = false, features = [
  "blocking",
  "json",
  "rustls-tls-native-roots",
] }
lazy_static = "*"
once_cell = { version = "*", features = ["std"] }
downcast = "*"
dotenvy = "0.15.7"

[profile.ephemeral]
opt-level = 1
codegen-units = 8
inherits = "release"
