version: "3.8"
services:
  client:
    container_name: bostil-bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - database:/app/src/public/database

volumes:
  database:
