version: "3.8"
services:
  client:
    container_name: bostil-bot-client
    image: ghcr.io/kszinhu/bostil-bot:master
    restart: unless-stopped
    networks:
      - kszinhu
    env_file:
      - stack.env

  database:
    container_name: bostil-bot-database
    image: postgres:16
    restart: unless-stopped
    networks:
      - kszinhu
    volumes:
      - bostil-database:/var/lib/postgresql/data
    env_file:
      - stack.env

volumes:
  bostil-database:
networks:
  kszinhu:
    name: kszinhu
    external: true
