version: "3.8"
services:
  client:
    container_name: bostil-client
    image: ghcr.io/kszinhu/bostil-bot:master
    restart: unless-stopped
    networks:
      - kszinhu
    env_file:
      - stack.env
    volumes:
      - database:/app/public/database

volumes:
  database:
networks:
  kszinhu:
    name: kszinhu
    external: true
