version: "3.8"
services:
  client:
    container_name: bostil-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database

  database:
    container_name: bostil-bot-db
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
      - .env.local
    ports:
      - "5432:5432"

volumes:
  db-data:
