[package]
name = "bostil-bot"
repository = "https://github.com/kszinhu/bostil-bot"
version = "0.2.0"
description = """
  Bostil Discord Bot
"""
authors.workspace = true
edition.workspace = true

[dependencies]
# Internal crates
bostil-core = { path = "../core" }

# Discord (Main dependencies)
serenity.workspace = true
songbird.workspace = true
reqwest.workspace = true
tokio = { features = ["full"], version = "1.21.2" }
symphonia = { features = ["aac", "mp3", "isomp4", "alac"], version = "0.5" }

# Database
postgres.workspace = true
dotenvy.workspace = true
diesel.workspace = true
diesel_migrations.workspace = true
chrono.workspace = true
uuid = { version = "^1.4.1", features = ["v4", "fast-rng"] }
time = "0.3"

# Logging
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-futures.workspace = true

# Internationalization (yml)
rust-i18n.workspace = true
serde_yaml.workspace = true

# Other
lazy_static.workspace = true
once_cell.workspace = true
downcast.workspace = true

# Potentially remove later
openssl = "*"
