# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::sql_types::SqlType", "std::fmt::Debug"]
import_types = [
  "diesel::sql_types::*",
  "crate::modules::core::entities::exports::*",
]

[migrations_directory]
dir = "migrations"
