CREATE TABLE users (
  id BIGINT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  added_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);